### ISSUE TITLE
Wrong Legend in "Distance Map" Widget

### ISSUE THREAD

**Issue by ubks** [biolab/orange#15]
Hi,
I think there is an issue with the "Distance Map" widget or the "Distances" Widget
I have calculated the Pearson Correlation Coefficient for my data.
As you can see in the attached picture the legend is labeled from 0.00 to 0.9.
But this is not true. The normal Pearson Correlation Coefficient can assume values between +1 and −1.
The perfect correlation is 1 and is present on the diagonal.
According to your legend it should be 0.
Additionally there seem to be no negative values, this might be true for "Absolute Pearson Correlation", but since I know there are negative correlations in my data, something must be wrong here.
I hope you can fix that.
THX
Mark

![graph](https://cloud.githubusercontent.com/assets/11298403/6467371/fb15dbac-c1cd-11e4-8443-785981b11bda.PNG)

**Comment by ubks** [comment]
please delete this issue

**Comment by janezd** [comment]
Can't. See, e.g., https://github.com/isaacs/github/issues/253.
