### ISSUE TITLE
Feature widget substraction issue?

### ISSUE THREAD

**Issue by reportbug1** [biolab/orange#19]
When creating a new column by subtracting two continous variables zero is given as a result.

Widgets used:
predictions + select attributes + feature + data table to check

**Comment by ales-erjavec** [comment]
I cannot duplicate this. Can you provide a more detailed report?

**Comment by reportbug1** [comment]
forgot to mention,
this only happened to me when trying to mix attributes/(class)/meta attributes in the feature,
trying to repeat it myself, but can't repeat it,
ignore this issue, if i can't repeat it
will close it for now
