### ISSUE TITLE
Orange Function to Read RData Files

### ISSUE THREAD

**Issue by snewhouse** [biolab/orange#25]
Hi Orange Dev Team - any plans to include functionality  for readlng and loading RData files/objects?
Running the following version of Orange:- 
![screen shot 2015-05-17 at 10 16 36](https://cloud.githubusercontent.com/assets/6317143/7669783/d93ac9e4-fc7d-11e4-9d29-3a27b0ebd627.png)

**Comment by janezd** [comment]
As far as I know, parsing .Rdata files requires rpy (and R). We wouldn't like add too many dependencies, especially if the same effect can be achieved by saving the R data in text format.

**Comment by snewhouse** [comment]
makes sense. I was having a brain dump at the time - and was lazy to open some test data in R and save as txt....
Cheers
