### ISSUE TITLE
Continuize Widget corruptes scheme ows file

### ISSUE THREAD

**Issue by acumhur** [biolab/orange#26]
After adding Continuize widget into my ows scheme and saving the scheme file corrupts the scheme file:
- The file size increases dramaticallly. For my case it was from 170KB to 7.1MB
- When I try to reopen the scheme file, orange crashes; "segmentation fault (core dumped)"

Then I opened the scheme file in a text editor and I noticed that for Continuize widget properties there are very long and garbage like entries. When I delete the properties entry for Continuize widget and save the scheme then Orange was able to load the scheme.

Example for garbage like entry:
(dbS'\xee\n\x00\x00\x00\x00\x00\x9aB\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x04\xbd\x01\x00\x00\x00\x00\x18B\x00\x00\x00\x00@@\x03\x00\x00\x00\x00\x05\xbd\x01\x00\x00\x00\x00\x00B\x00\x00\x00\x80?@\x03\x00\x00\x00\x00\x06\xbd\x01\x00\x00\x00\x00\x8cB\x00\x00\x00\x00\x00@\x03\x00\x00\x00\x00\x07\xbd\x01\x00\x00\x00\x00\x88A\x00\x00\x00\x00\x00@\x03\x00\x00\x00\x00\x08\xbd\x01\x00\x00\x00\x00\x98B\x00\x00\x00\x00\x00@\x03\x00\x00\x00\x00\t\xbd\x01\x00\x00\x00\x00,B\x00\x00\x00\x00@@\x03\x00\x00\x00\x00\n\xbd\x01\x00\x00\x00\x00\xaaB\x00\x00\x00\x80?@\x03\x00\x00\x00\x00\x0b\xbd\x01\x00\x00\x00\x00tB\x00\x00\x00\x00\x00@\x03\x00\x00\x00\x00\x0c\xbd\x01\x00\x00\x00\x00\xb8A\x00\x00\x00\x80@@\x04\x00\x00\x00\x00\r\xbd\x01\x00\x00\x00\x00tB\x00\x00\x00@@@\x04\x00\x00\x00\x00\x0e\xbd\x01\x00\x00\x00\x00\xe0A\x00\x00\x00@@@\x04\x00\x00\x00\x00\x0f\xbd\x01\x00\x00\x00\x00\x08B\x00\x00\x00\x80@@\x04\x00\x00\x00\x00\x10\xbd\x01\x00\x00\x00\x00\x10B\x00\x00\x00\x80@@\x04\x00\x00\x00\x00\x11\xbd\x01\x00\x00\x00\x00\x10B\x00\x00\x00\x80@@\x04\x00\x00\x00\x00\x12\xbd\x01\x00\x00\x00\x00\x98B\x00\x00\x00@@@\x05\x00\x00\x00\x00\x13\xbd\x01\x00\x00\x00\x00\x18B\x00\x00\x00@@@\x05\x00\x00\x00\x00\x14\xbd\x01\x00\x00\x00\x00pA\x00\x00\x00\x00@@\x05\x00\x00\x00\x00\x15\xbd\x01\x00\x00\x00\x00\x10B\x00\x00\x00@@@\x05\x00\x00\x00\x00\x16\xbd\x01\x00\x00\x00\x00\xc8A\x00\x00\x00\xa0@@\x05\x00\x00\x00\x00\x17\xbd\x01\x00\x00\x00\x00(B\x00\x00\x00\x80@@\x05\x00\x00\x00\x00\x18\xbd\x01\x00\x00\x00\x00\x08B\x00\x00\x00\x80@@\x05\x00\x00\x00\x00\x19\xbd\x01\x00\x00\x00\x00\x08B\x00\x00\x00\x80@@\x05\x00\x00\x00\x00\x1a\xbd\x01\x00\x00\x00\x00\xd8A\x00\x00\x00@@@\x05\x00\x00\x00\x00\x1b\xbd\x01\x00\x00\x00\x00\x00B\x00\x00\x00\x00@@\x05\x00\x00\x00\x00\x1c\xbd\x01\x00\x00\x00\x00\x90B\x00\x00\x00\x80?@\x05\x00\x00\x00\x00\x1d\xbd\x01\x00\x00\x00\x00\xa0A\x00\x00\x00@@@\x05\x00\x00\x00\x00\x1e\xbd\x01\x00\x00\x00\x00@B\x00\x00\x00@@@\x05\x00\x00\x00\x00\x1f\xbd\x01\x00\x00\x00\x00\xe8A\x00\x00\x00\x80@@\x05\x00\x00\x00\x00 \xbd\x01\x00\x00\x00\x00(B\x00\x00\x00\x80@@\x05\x00\x00\x00\x00!\xbd\x01\x00\x00\x00\x00\x08B\x00\x00\x00\x80@@\x05\x00\x00\x00\x00"\xbd\x01\x00\x00\x00\x00\xc0A\x00\x00\x00@@@\x05\x00\x00\x00\x00#\xbd\x01\x00\x00\x00\x00\x96B\x00\x00\x00@@@\x05\x00\x00\x00\x00$\xbd\x01\x00\x00\x00\x00\xb8A\x00\x00\x00\xe0@@\x05\x00\x00\x00\x00%\xbd\x01\x00\x00\x00\x00\x08B\x00\x00\x00@@@\x05\x00\x00\x00\x00&amp;\xbd\x01\x00\x00\x00\x00\x98A\x00\x00\x00\x80@@\x05\x00\x00\x00\x00\'\xbd\x01\x00\x00\x00\x00&lt;B\x00\x00\x00@@@\x05\x00\x00\x00\x00(\xbd\x01\x00\x00\x00\x00\x00B\x00\x00\x00@@@\x05\x00\x00\x00\x00)\xbd\x01\x00\x00\x00\x00\x0cB\x00\x00\x00@@@\x05\x00\x00\x00\x00*\xbd\x01\x00\x00\x00\x00\x96B\x00\x00\x00@@@\x05\x00\x00\x00\x00+\xbd\x01\x00\x00\x00\x00\x90A\x00\x00\x00@@@\x05\x00\x00\x00\x00,\xbd\x01\x00\x00\x00\x00\xc8A\x00\x00\x00@@@\x05\x00\x00\x00\x00-

**Comment by acumhur** [comment]
I also found out that in my home folder ~/.orange/widgetSettingsQt4/Orange.OrangeWidgets.Data.OWContinuize.OWContinuize.pck file size is 15MB while the others are no more than 8KB.

**Comment by ales-erjavec** [comment]
The problem was that Continuize widget would (by mistake) store the entire input data-sets in its settings. I'm not sure how the settings got corrupted (I was not able to duplicate the crash). Can you upload a example .ows file somewhere?

The problem should be fixed in the current master branch. However you will have to delete the ~/.orange/widgetSettingsQt4/Orange.OrangeWidgets.Data.OWContinuize.OWContinuize.pck file, as well as all corrupted .ows files.

**Comment by acumhur** [comment]
After deleting ~/.orange/widgetSettingsQt4/Orange.OrangeWidgets.Data.OWContinuize.OWContinuize.pck and using Continuize widget did not cause any problems. It works as expected. 
Ows file size increases proportional to dataset size (probably because of storing entire data as you mentioned). Not a bug, but would be better if it didn't increase the file size dramatically.
My current Orange version is 2.7.8.dev-ed82809 (on Linux).

If the problem occurs again I will send the ows file and the pck file also.
Thanks for your help.
