### ISSUE TITLE
Why not a windows 64 binaries version ?

### ISSUE THREAD

**Issue by jamartinh** [biolab/orange#33]
Hi, is there any problem for generating a windows 64 binary distribution or the snapshot ?

Thanks,
Jose

**Comment by astaric** [comment]
Orange Snapshot is compiled against official release of numpy, which does not provide a 64bit binary version.
(We looked here http://sourceforge.net/projects/numpy/files/NumPy/1.9.2/ and did not find it.)

Sources however can be build into 64bit binaries, as there are unofficial sources that provide 64bit build of Orange, compiled against their own 64bit build of numpy.
(http://www.lfd.uci.edu/~gohlke/pythonlibs/#orange)
