### ISSUE TITLE
Widget Associate missing in GUI

### ISSUE THREAD

**Issue by Thorius94** [biolab/orange#36]
I recently installed Orange 3.2 and I noticed that Orange Canvas does not contain an Associate tab - the one for frequent patterns and such. I checked in the Python terminal that the library is there but there is no way to use it in the GUI interface. I looked around in the options to no avail.

I know this is present in the 2.x version of Orange. Can someone explain why it is missing in 3.2? Is it a bug?

For information, I am using Windows 10.

**Comment by janezd** [comment]
We haven't yet ported it to Orange 3. It's planned.
