### ISSUE TITLE
Orange Canvas will not open Windows 7

### ISSUE THREAD

**Issue by dstarobin** [biolab/orange#41]
Hello, 

I've attempted to install Orange (Win7, 64 bit), but it will not open. I have Python 2.7 as well as Python 3.4 installed (3.4 installed with Orange). Nothing happens when attempting to open the program. I've rebooted as well. I see Orange in C:\Python34\Lib\site-packages\Orange. Any help is appreciated.

Thanks.

**Comment by kernc** [comment]
If you open command prompt (cmd.exe) and paste in:
`C:\Python34\python.exe -m Orange.canvas -l 4`
What does it output?

**Comment by dstarobin** [comment]
Thanks for your quick response and sorry for my long delay. The message reads:
"Error while finding spec for 'Orange.canvas' (<class 'ImportError'>: DLL load failed: %1 is not a valid Win32 application.)

**Comment by kernc** [comment]
Ah, yes, due to NumPy, Orange only supports 32-bit Python on Windows. If you had Python preinstalled, you should install the one from Orange installed into another folder, like _C:\Python34_32_, and then also install Orange there.

**Comment by dstarobin** [comment]
Ok, thanks for your guidance. I'll do that.

**Comment by dstarobin** [comment]
Thanks again. In uninstalled Python 3.4 as well as Orange, then reinstalled via Orange's distribution. It worked perfectly.
