### ISSUE TITLE
Icons and buttons not visible after installing Orange 3.3.7 on Ubuntu 16.04

### ISSUE THREAD

**Issue by brylie** [biolab/orange#46]
After installing Orange 3.3.7 on Ubuntu 16.04, the user interface icons and buttons fail to render correctly.

![screenshot from 2016-07-05 15-43-02](https://cloud.githubusercontent.com/assets/17307/16585042/923b7430-42c7-11e6-88e0-b6e28b2d900e.png)

## Environment
- Ubuntu 16.04
- Orange 3.3.7
- Anaconda 3.x
- Python 3.5

**Comment by kernc** [comment]
Please install `libqt4-svg` package and see if that solves it.

**Comment by brylie** [comment]
Thanks for the quick support @kernc :smile:

**Comment by ajdapretnar** [comment]
@brylie Could you please refer to [Orange3 issue tracker](https://github.com/biolab/orange3/issues) for Orange3 related issues? Thanks! Closing this for the incorrect issue tracker and also since the issue seems to be solved. :smile: No harm I guess. :wink:

**Comment by brylie** [comment]
I had to do a Google search just to find this issue tracker. E.g. I could not figure out where to file issues from the orange.biolab.si website.

**Comment by brylie** [comment]
```
libqt4-svg is already the newest version (4:4.8.7+dfsg-5ubuntu2).
```

**Comment by ajdapretnar** [comment]
Reopening since the problem doesn't seem to be solved yet.

**Comment by brylie** [comment]
Cool, I am re-opening it in the proper issue tracker :wink:

**Comment by brylie** [comment]
Should we close this issue, since it is opened in orange3 issue tracker?
