### ISSUE TITLE
Save classifier

### ISSUE THREAD

**Issue by peterbjarke** [biolab/orange#50]
I am using orange 3.3.9 for Mac. I am unable to save a classifier (random forest regression). After selecting a filename and a directory the save file button is still grey. 

![image](https://cloud.githubusercontent.com/assets/4041556/21149232/23b706d8-c15b-11e6-9a95-d5bfcb7dceb2.png)

**Comment by ajdapretnar** [comment]
You are only sending a learner to Save Classifier, not a model. You need to feed the learner (e.g. Random Forest Regression) some data to build the model on, like this:

![classifier](https://cloud.githubusercontent.com/assets/12524972/21173578/a8e3bf90-c1d8-11e6-8d63-7086d3205f95.PNG)
