### ISSUE TITLE
Orange Canvas will not open Mac OS 10.9.5

### ISSUE THREAD

**Issue by umendi** [biolab/orange#55]
I have downloaded the last Orange3 version for Mac (Orange3-3.5.0.dmg), installed it as described and tried to open it using right click, open.

The orange icon appears briefly and then disappears. No GUI is loaded. I managed to keep the Orange3 icon on the dock but no matter what I do to open it it always automatically close without providing any system error.

I did not have any version of Python installed on this system (which was the issue I read here for another user with Windows 7).

**Comment by astaric** [comment]
Could you please open this issue on [orange3 repository](https://github.com/biolab/orange3)
The biolab/orange repository is for the legacy version of Orange, while everything related to Orange3 has been moved to the new repository.

**Comment by umendi** [comment]
Sorry about it. I opened over there. Closing it here.
