### ISSUE TITLE
Why I got diff

### ISSUE THREAD

**Issue by QiChen2014** [biolab/orange#58]
Hi everyone! 
I have some perplexing questions while using Orange(version 3.11). I sampled a subset from the input dataset by Data Sampler widget to train a Logistic Regression , parameters like this:
<prep>
Sampling type: Random sample with 70 % of data, stratified (if possible), deterministic
Input: 178 instances
Sample: 125 instances
Remaining: 53 instances
</prep>
then I used the Test&Score widget to see the result by setting "Stratified 10-fold Cross validation" and I got the result like this:
<prep>
Method AUC CA F1 Precision Recall
Logistic Regression 0.751 0.776 0.757 0.756 0.776
</prep>
the test result on testdata like this:
<prep>
Method AUC CA F1 Precision Recall
Logistic Regression 0.709 0.736 0.709 0.704 0.736
</prep>
After that, I extracted the trainning data and test data which sampled by the  Data Sampler widget  with a python program, and used the trainning data to train a Logistic Regression model(parameter is the same like previous) , used the test data to validate the model, but I got the different result both in trainning and testing(all the parameters are the same), why? 
Another question is how to output the detail parameters when sampling (i.e. the random seed and the test data), is it feasible? 
Maybe these questions are quite stupid, I hope to get your help, thanks!

**Comment by ajdapretnar** [comment]
This is an old Orange repository. Since the question in concerning version 3, please refer to the corresponding [repository](https://github.com/biolab/orange3/issues). Best to ask questions, where they will be seen. :)

**Comment by QiChen2014** [comment]
@ajdapretnar Thanks a lot, I will ask in the new repository😀
