### ISSUE TITLE
Why does Test & Score take all day?

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange#59]
That was an exageration.

But for 10,000 test samples it takes like 30mins- 1 hour, which doesn't make sense.  All its doing is running a sample by the NN.

Please explain to me why this should take all day.

Thanks.

**Comment by kernc** [comment]
What sampling method is selected? Leave-one-out could be slow as the routine is repeated 10,000 times.

**Comment by enjoysmath** [comment]
Test on test data

**Comment by markotoplak** [comment]
As you are saying, prediction should be fast. I can not say for sure, but I would guess that in your case building a model takes most of the time (within test and score a model is built on learning data and evaluated on test data).

Try if such behavior persist with other modeling techniques. If it does not, decrease the complexity of your neural networks.
